services:

  miniohotels:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '9090:9090'
    env_file: minioproducts.env
    networks:
      - s3-data
    volumes:
      - 'minio-data:/data'
    command: server --console-address ":9090" /data
    restart: always

  mysqldbhotels:
    platform: linux/x86_64
    image: mysql:5.7   
    container_name: mysqldbproducts
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: hotelinformation
      MYSQL_USER: test
      MYSQL_PASSWORD: testpassword
      TZ: Europe/Berlin
    ports:
      - "3306:3306"
    volumes:
      - mysqlVolumeProducts:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
      
  phpmyadminhotels:
    image: phpmyadmin/phpmyadmin  
    container_name: phpadminhotels
    environment:
      PMA_HOST: mysqldbhotels
    restart: always
    ports:
      - 8081:80
 
volumes:
  minio-data:
    driver: local
  mysqlVolumeProducts:


networks:
  mysql-phpmyadmin:

  s3-data:
    driver: bridge