services:

  miniohotels:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '9090:9090'
    env_file: miniorooms.env
    networks:
      - s3-data
    volumes:
      - 'minio-data:/data'
    command: server --console-address ":9090" /data
    restart: always

  mysqldbhotels:
    platform: linux/x86_64
    image: mysql:5.7   
    container_name: mysqldbrooms
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: hotelrooms
      MYSQL_USER: test
      MYSQL_PASSWORD: testpassword
      TZ: Europe/Berlin
    ports:
      - "3306:3306"
    volumes:
      - mysqlVolumeHotels:/var/lib/mysql
      - ./database_setup_rooms.sql:/docker-entrypoint-initdb.d/database_setup_rooms.sql
      
  phpmyadminhotels:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin  
    container_name: phpadminhotels
    environment:
      PMA_HOST: mysqldbhotels
    restart: always
    ports:
      - 8080:80


  mysqldbevents:
      platform: linux/x86_64
      image: mysql:5.7   
      container_name: mysqldbevents
      environment:
        MYSQL_ROOT_PASSWORD: testpassword
        MYSQL_DATABASE: events
        MYSQL_USER: test
        MYSQL_PASSWORD: testpassword
        TZ: Europe/Berlin
      ports:
        - "3310:3310"
      volumes:
        - mysqlVolumeEvents:/var/lib/mysql
        - ./database_setup_events.sql:/docker-entrypoint-initdb.d/database_setup_events.sql
        
  phpmyadminevents:
      platform: linux/x86_64
      image: phpmyadmin/phpmyadmin  
      container_name: phpadminevents
      environment:
        PMA_HOST: mysqldbevents
      restart: always
      ports:
        - 8081:80


 
volumes:
  minio-data:
    driver: local
  mysqlVolumeHotels:
  mysqlVolumeEvents:

networks:
  s3-data:
    driver: bridge